// app/layout.js
import { Noticia_Text } from "next/font/google";
import "./globals.css";


const noticia = Noticia_Text({
  variable: "--font-noticia",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${noticia.variable} font-noticia`} style={{ perspective: '1000px' }}>
        {children}
      </body>
    </html>
  );
}
